
# Networks ############################################################################################################

networks:
  cardano:
    name: cardano
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

# Services ############################################################################################################

services:

  # Relay -------------------------------------------------------------------------------------------------------------

  relay:
    image: nessusio/cardano-node:${CARDANO_NODE_VERSION:-latest}
    container_name: relay
    restart: unless-stopped
    hostname: relay
    networks:
      cardano:
    ports:
      - "3001:3001"
    environment:
      CARDANO_TOPOLOGY: '{
          "Producers": [
            {
              "addr": "relays-new.cardano-mainnet.iohk.io",
              "port": 3001,
              "valency": 1
            },
            {
              "addr": "${CARDANO_BPROD_IP}",
              "port": 3001,
              "valency": 1
            }
          ]
        }'
      CARDANO_CUSTOM_PEERS: "${CARDANO_BPROD_IP}:3001"
      CARDANO_UPDATE_TOPOLOGY: "true"
    command: "run"
    volumes:
      - node-data:/opt/cardano/data

  # Monit -------------------------------------------------------------------------------------------------------------

  monit:
    image: nessusio/monit
    container_name: monit
    restart: unless-stopped
    hostname: monit
    networks:
      cardano:
    command: ["-Iv"]
    volumes:
      - monit-config:/etc/monit.d

  # NGINX -------------------------------------------------------------------------------------------------------------

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    hostname: nginx
    networks:
      cardano:
    ports:
      - "12798:80"
    volumes:
      - nginx-config:/etc/nginx:ro

# Volumes #############################################################################################################

volumes:
  node-data:
    external: true
  monit-config:
    external: true
  nginx-config:
    external: true
