version: "3.5"

services:
  postgres:
    image: postgres:11.5-alpine
    container_name: cardano-postgres
    restart: "no"
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - postgres:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-node:
    image: nessusio/cardano-node:1.29.0
    container_name: cardano-node
    restart: "no"
    ports:
      - ${NODE_PORT:-3001}:3001
    command: "run"
    volumes:
      - node-data:/opt/cardano/data
      - node-ipc:/opt/cardano/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-db-sync:
    image: inputoutput/cardano-db-sync:11.0.0
    container_name: cardano-db-sync
    restart: "no"
    environment:
      - NETWORK=${NETWORK:-mainnet}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - db-sync-data:/var/lib/cdbsync
      - node-ipc:/node-ipc
    depends_on:
      - cardano-node
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

secrets:
  postgres_db:
    file: ~/cardano/secrets/postgres_db
  postgres_password:
    file: ~/cardano/secrets/postgres_password
  postgres_user:
    file: ~/cardano/secrets/postgres_user

volumes:
  db-sync-data:
  postgres:
  node-data:
    external: true
  node-ipc:
    external: true
